# Generated by Django 3.1.6 on 2021-02-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Post_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='categorys',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='report',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
