# Generated by Django 3.1.6 on 2021-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210217_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/https:/https://i.imgur.com/iwqmcAT.jpg', upload_to=''),
        ),
    ]
