# Generated by Django 3.1.6 on 2021-02-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categorys_comment_post_report_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
