# Generated by Django 3.1.6 on 2021-02-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='test.png', upload_to=''),
        ),
    ]
