# Generated by Django 3.1.6 on 2021-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210218_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_img/profile.png', upload_to='profile_img/'),
        ),
    ]
