# Generated by Django 3.1.6 on 2021-02-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210218_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Post_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
