# Generated by Django 3.1.6 on 2021-02-24 15:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_comment_likes_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorys', verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Post Content:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='isPublish',
            field=models.CharField(choices=[('notPublished', 'notPublished'), ('published', 'published'), ('refused', 'refused'), ('draft', 'draft')], default='notPublished', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='post_img/test.png', upload_to='post_img/', verbose_name='Post Header:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='about_me',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About me:'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_img/profile.png', upload_to='profile_img/', verbose_name='Picture:'),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
